### ISSUE TITLE
Does not work on PHP 8

### ISSUE THREAD

**Issue by davehowson** [mbezhanov/faker-provider-collection#14]
I get the following error when I try to run composer require.

> 
>  [InvalidArgumentException]
>  Package mbezhanov/faker-provider-collection has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

PHP 8.0
Composer 2.0.7

**Comment by mbezhanov** [comment]
Thank you for reporting this. I have just released version 2.0.0 which provides support for PHP 8.0. I will go ahead and close this issue, since I believe it has been resolved.
