### ISSUE TITLE
Laravel 8 Installation Issue

### ISSUE THREAD

**Issue by RobertHowdle** [mbezhanov/faker-provider-collection#15]
Hello! Thank you for creating this package. I'm having some trouble installing it on Laravel 8. Running the following commands:
`composer require --dev mbezhanov/laravel-faker-provider-collection` OR `composer require mbezhanov/faker-provider-collection` returns the following error and I cannot seem to work out how I can get past this.

My current set up is using Laravel 8 with Docker if that at all helps.

**Error:**
```
Using version ^1.2 for mbezhanov/laravel-faker-provider-collection
./composer.json has been updated
Running composer update mbezhanov/laravel-faker-provider-collection
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mbezhanov/laravel-faker-provider-collection ^1.2 -> satisfiable by mbezhanov/laravel-faker-provider-collection[1.2.0].
    - mbezhanov/laravel-faker-provider-collection 1.2.0 requires illuminate/support ^5.1|^6.0|^7.0 -> found illuminate/support[v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

If you are able to advise on what I may be doing wrong I'd be very grateful, Thank you!

Rob

**Comment by mbezhanov** [comment]
Hi, thank you for reporting this issue. A new version of `laravel-fake-provider-collection` has just been released to address the issue you have described and it should solve the problem: https://packagist.org/packages/mbezhanov/laravel-faker-provider-collection#2.0.0

If you require any further assistance feel free to reopen this issue.
