### ISSUE TITLE
Laravel setup

### ISSUE THREAD

**Issue by ghost** [mbezhanov/faker-provider-collection#2]
Hi,
Would be possible to use this with laravel?

I found this answer, but im not sure how to glue this library with those directions

https://stackoverflow.com/questions/38250776/how-to-implement-your-own-faker-provider-in-laravel

**Comment by mbezhanov** [comment]
Sure. Here's how:

1. Navigate to the root dir of your Laravel project
2. Install the library: `composer require --dev mbezhanov/faker-provider-collection`
3. Create a new service provider for Faker (either  `php artisan make:provider FakerServiceProvider` or `touch ./app/Providers/FakerServiceProvider.php`
4. In `./app/Providers/FakerServiceProvider.php` paste the following code:
    
    ```php
    <?php
    
    namespace App\Providers;
    
    use Bezhanov\Faker\ProviderCollectionHelper;
    use Faker\Factory;
    use Faker\Generator;
    use Illuminate\Support\ServiceProvider;
    
    class FakerServiceProvider extends ServiceProvider
    {
        public function register()
        {
            $this->app->singleton(Generator::class, function () {
                $faker = Factory::create();
                ProviderCollectionHelper::addAllProvidersTo($faker);
    
                return $faker;
            });
        }
    }
    ```
5. Finally, register the new provider with your application, by adding `App\Providers\FakerServiceProvider::class,` to the `providers` array in `./config/app.php`

You should now be able to use the all the extra providers bundled with this library in your Model Factories, e.g.

```php
<?php

// ./database/factories/UserFactory.php

use Faker\Generator as Faker;

$factory->define(App\User::class, function (Faker $faker) {
    return [
        'name' => $faker->name,
        'university' => $faker->university,
        'sport' => $faker->sport,
        'team' => $faker->team,
    ];
});
```

Let me know if you have any further questions.

**Comment by ghost** [comment]
Nops. Very thanks! :)
(i will try to translate this to pt-BR, but you allready gave me all the lights i would need)
Very thanks again.
