### ISSUE TITLE
Move php-mock/php-mock: ^2.0 to require-dev

### ISSUE THREAD

**Issue by c33s** [mbezhanov/faker-provider-collection#4]
shouldn't `php-mock/php-mock: ^2.0` be only required in dev? the only class i found it was `SpeciesTest`  (`use phpmock\MockBuilder;`)

**Comment by mbezhanov** [comment]
Hello @c33s,

Thank you very much for reporting this issue. You are absolutely right, `php-mock` - should be a dev dependency, but it seems I forgot to double-check this before publishing version `1.2.0`.

Version `1.2.1` now fixes this issue.
