### ISSUE TITLE
Add to Bezhanov\Faker\Provider\Commerce a ProductDescription

### ISSUE THREAD

**Issue by HamzaDevz** [mbezhanov/faker-provider-collection#5]
Hello,

First thanks for this library.

Is it possible to add a ProductDescription to Bezhanov\Faker\Provider\Commerce ?

Thank you by advance.

**Comment by mbezhanov** [comment]
Hello @HamzaDevz,

What kind of content would you like the ProductDescription generator to create? I usually use https://github.com/fzaninotto/Faker#fakerproviderlorem for generating longer descriptions.

**Comment by mbezhanov** [comment]
I am closing the issue due to lack of activity.
